mysite/mysite/urls.py
from django.conf.urls import include,url,static,patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('xodia.urls' , namespace="xodia" )),

  ]

"""urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += patterns('',
        (r'^media/(?P<path>.*)',
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}), )""" 

mysite/xodia/urls.py
from django.conf.urls import url,patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from mysite import settings
import views 


urlpatterns = [      
                   url(r'^$',views.homepage,name="homepage"),
                   #url(r'^sign_up/$',views.signup,name="signup"),
                   url(r'^log_in/$',views.login_view, name="login"),
                   #url(r'^signuppage/$',views.signuppage, name="signuppage"),
                   #url(r'^loginpage/$',views.loginpage, name="loginpage"),
                   url(r'^logout/$',views.logout_view,name="logout"),
                   url(r'^personal_homepage/$',views.personal_home ,name="personal_home"),
                   #url(r'^test/$',views.test,name="test"),
                   #url(r'^submit/$',views.submit,name="submit"),
                   #url(r'^testpage/$',views.testpage,name="testpage"),
                   #url(r'^get_game/$',views.gettestgame,name="getgame"),
                   url(r'^clickable/$',views.clickable,name="clickable"),
                   #url(r'^nolang/$',views.nolang,name="nolang" ),
                   url(r'^genmatches/$',views.genmatches,name="genmatches"),
      ]
                   
"""urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += patterns( '',
        (r'^media/(?P<path>.*)',
         'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}), )"""

mysite/xodia/models.py
from django.contrib.auth.models import User
from django.db import models
import mysite.settings
from os import path

# Create your models here.

class UserData(models.Model):
    user            = models.OneToOneField(User)
    won             = models.IntegerField(default=0)
    lost            = models.IntegerField(default=0)
    draw            = models.IntegerField(default=0)
    points          = models.IntegerField(default=0)
    bot_path1       = models.CharField(max_length = 200)
    bot_path2       = models.CharField(max_length = 200)
    bot_pathf       = models.CharField(max_length = 50)
    test_no         = models.IntegerField(default = 0)
    submitted       = models.IntegerField(default = 0)
    loginattempt    = models.IntegerField(default = 0)
    mobno           = models.CharField(max_length = 13)
    profilepic      = models.ImageField(max_length = 4000)

mysite/xodia/views.py
from django.shortcuts import render
from models import UserData
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from os import path,chdir,system
from subprocess import Popen,PIPE
import mysite.settings
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import tempfile
# Create your views here.

def homepage(request):
	u = request.user
	if u.is_authenticated():
		return HttpResponseRedirect(reverse('xodia:personal_home'))
	else:
		return render(request,'xodia/index.html')
	
		

def signuppage(request):
	u = request.user
	if u.is_authenticated():
		return HttpResponseRedirect(reverse('xodia:personal_home'))
	else:
		return render(request,'xodia/login.html')
		

"""@csrf_exempt
def loginpage(request):
	u = request.user
	if u.is_authenticated():
		return HttpResponseRedirect(reverse('xodia:personal_home'))
	else:
		return render(request,'xodia/login.html')"""
		


def signup(request):
	u = request.user
	if u.is_authenticated():
		return HttpResponseRedirect(reverse('xodia:personal_home'))
	else:
		for exist_user in User.objects.all():
			if request.POST['uname'] == exist_user.username:
				return render(request,'xodia/alreadyuname.html')
    	
    	u = User.objects.create_user(username = request.POST['uname'] , first_name = request.POST['fname'] , last_name = request.POST['lname'] )
        u.email = request.POST['email']
    	u.set_password(request.POST['password'])
    	u.save()
    	ud  = UserData(user = u)
    	if 'dp' in request.FILES:
    		ud.profilepic  = request.FILES['dp']

    	else:
    		ud.profilepic  = path.join(mysite.settings.BASE_DIR,'static/xodia/dps/images_004.png')
    		#ud.profilepic = '/home/lite/xodia_web_engine/mysite/xodia/static/xodia/dps/11070092_1026956053989421_6069066535809089795_o.jpg'
    	ud.mobno = request.POST['mobno']
        ud.save()
    	print 'Before'
    	u.backend = 'django.contrib.auth.backends.ModelBackend'
    	login(request,u)
    	print 'After'
    	return HttpResponseRedirect(reverse('xodia:personal_home'))


    

def login_view(request):
    username = request.POST['uname']
    password = request.POST['password']

    """for u in User.objects.all():
    	if u.username == username:
    		if u.password == password:
    			flag = 1
    		else:
    			flag = 0
    	else:
    		flag=0"""

    u = authenticate(username = username , password = password)

    if u is not None:
    	if u.is_active:
    		#u.backend = 'django.contrib.auth.backends.ModelBackend'
    		login(request,u)
    		dppath = u.userdata.profilepic.name[len(mysite.settings.BASE_DIR) + 8:]
    		return HttpResponseRedirect(reverse('xodia:personal_home'))
    	else:
    		return HttpResponse("Not Active User")

    else: 
    	return render(request,'xodia/invalid_user_pwd.html')


@login_required(login_url='/')
def testpage(request,message=""):
	
	u = request.user
	if 'error' in request.session:
		message = request.session['error'] 
	print message
	request.session['error'] = ""
	dppath = u.userdata.profilepic.path[len(mysite.settings.BASE_DIR) + 8 :]
	acevalue1 = ""
	acevalue2 = ""
	acevaluef = ""	
	load_path =  path.join(mysite.settings.BASE_DIR,'xodiaxyz/playerone')
	
	if u.userdata.submitted == 1:
		bot_pathf = u.userdata.bot_pathf
		testfilef = path.join(load_path,bot_pathf)
		f = open(testfilef,'r')
		acevaluef = f.read()
		f.close() 


	elif u.userdata.test_no == 1:
		bot_path = u.userdata.bot_path1
		testfile = path.join(load_path,bot_path)
		f = open(testfile,'r')
		acevalue1 = f.read()
		f.close()
	elif u.userdata.test_no == 2:
		bot_path = u.userdata.bot_path2
		testfile = path.join(load_path,bot_path)
		f = open(testfile,'r')
		acevalue2 = f.read()
		f.close()

	elif u.userdata.test_no == 3:
		bot_path1 = u.userdata.bot_path1
		bot_path2 = u.userdata.bot_path2
		testfile1 = path.join(load_path,bot_path1)
		testfile2 = path.join(load_path,bot_path2)
		f = open(testfile1,'r')
		acevalue1 = f.read()
		f.close()
		f = open(testfile2,'r')
		acevalue2 = f.read()
		f.close()

	

	if u.userdata.submitted == 1:
		return render(request,'xodia/submitted.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2, 'acevaluef':acevaluef ,'message': message })
	elif u.userdata.test_no == 0:
		return render(request,'xodia/test.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef , 'message' : message })
	elif u.userdata.test_no == 1 or u.userdata.test_no == 2 :
		return render(request,'xodia/test1.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef , 'message' : message })
	elif u.userdata.test_no == 3 :
		return render(request,'xodia/test2.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef ,'message' : message }) 
	
def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('xodia:homepage'))


@csrf_exempt    
@login_required(login_url = '/xodia/loginpage')
def personal_home(request):
	u = request.user
	dppath = u.userdata.profilepic.path[len(mysite.settings.BASE_DIR) + 8 :]
	return render(request,'xodia/indexlogged.html',{'user':u,'dppath':dppath})


def clickable(request):
	return render(request,'xodia/clickable.html')





"""def codeinput(request,user_id):
	action = request.POST.get('action')

	if action == 'test' :
		return HttpResponseRedirect(reverse('xodia:test', args=(user_id,)))

	if action == 'Submit' :
		return HttpResponseRedirect(reverse('xodia:submit', args=(user_id,))) """


def nolang(request):
	u = request.user
	if 'error' in request.session:
		message = request.session['error'] 
	print message
	request.session['error'] = ""
	dppath = u.userdata.profilepic.path[len(mysite.settings.BASE_DIR) + 8:]
	acevalue1 = ""
	acevalue2 = ""
	acevaluef = ""	
	load_path =  path.join(mysite.settings.BASE_DIR,'xodiaxyz/playerone/')
	if u.userdata.test_no == 1:
		bot_path = u.userdata.bot_path1
		testfile = path.join(load_path,bot_path)
		f = open(testfile,'r')
		acevalue1 = f.read()
		f.close()
	elif u.userdata.test_no == 2:
		bot_path = u.userdata.bot_path2
		testfile = path.join(load_path,bot_path)
		f = open(testfile,'r')
		acevalue2 = f.read()
		f.close()

	elif u.userdata.test_no == 3:
		bot_path1 = u.userdata.bot_path1
		bot_path2 = u.userdata.bot_path2
		testfile1 = path.join(load_path,bot_path1)
		testfile2 = path.join(load_path,bot_path2)
		f = open(testfile1,'r')
		acevalue1 = f.read()
		f.close()
		f = open(testfile2,'r')
		acevalue2 = f.read()
		f.close()

	elif u.userdata.submitted == 1:
		both_pathf = u.userdat.bot_pathf
		testfilef = path.join(load_path,bot_pathf)
		f = open(testfilef,'r')
		acvaluef = f.read()
		f.close() 


	
	if u.userdata.test_no == 0:
		return render(request,'xodia/nolang.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef , 'message' : message })
	elif u.userdata.test_no == 1 or u.userdata.test_no == 2 :
		return render(request,'xodia/nolang1.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef , 'message' : message })
	elif u.userdata.test_no == 3 :
		return render(request,'xodia/nolang2.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2 ,'acevaluef':acevaluef ,'message' : message }) 
	elif u.userdata.submitted == 1:
		return render(request,'xodia/submitted.html',{'user':u ,'dppath':dppath , 'acevalue1': acevalue1 , 'acevalue2' : acevalue2, 'acevaluef':acevaluef ,'message': message })



@login_required(login_url = '/xodia/loginpage')
def test(request):
	u = request.user
	if u.is_authenticated():
		s = request.POST['code']
		test_no = request.POST['test_no']
		if u.userdata.test_no == 1 and test_no == 1 :
			del_path1 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playerone/'
			del_path2 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playertwo/'
			system('rm ' + del_path1 + str(u.userdata.bot_path1))
			system('rm ' + del_path2 + str(u.userdata.bot_path1))

		elif u.userdata.test_no == 2 and  test_no == 2 :
			del_path1 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playerone/'
			del_path2 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playertwo/'
			system('rm ' + del_path1 + str(u.userdata.bot_path2))
			system('rm ' + del_path2 + str(u.userdata.bot_path2))

		elif u.userdata.test_no == 3:
			if test_no == 1:
				del_path1 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playerone/'
				del_path2 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playertwo/'
				system('rm ' + del_path1 + str(u.userdata.bot_path1))
				system('rm ' + del_path2 + str(u.userdata.bot_path1))
			elif test_no == 2:
				del_path1 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playerone/'
				del_path2 = '/var/lib/lxc/zango/rootfs/home/ubuntu/xodiaxyz/playertwo/'
				system('rm ' + del_path1 + str(u.userdata.bot_path2))
				system('rm ' + del_path2 + str(u.userdata.bot_path2))

				
		save_path1 = path.join(mysite.settings.BASE_DIR,'xodiaxyz/playerone/')
		save_path2 = path.join(mysite.settings.BASE_DIR,'xodiaxyz/playertwo/')

		if request.POST['lang'] == 's1':
			return HttpResponseRedirect(reverse('xodia:nolang'))
			

		elif request.POST['lang'] == 'c':
			if test_no == "test1" :
				u.userdata.bot_path1 = u.username + "test1" + ".c"
				bot_path = u.userdata.bot_path1
				if u.userdata.test_no == 2:
					u.userdata.test_no = 3
				elif u.userdata.test_no == 0:
					u.userdata.test_no = 1 
				
			elif test_no == "test2" :
				u.userdata.bot_path2 = u.username + "test2" + ".c"
				bot_path = u.userdata.bot_path2
				if u.userdata.test_no == 1:
					u.userdata.test_no = 3
				elif u.userdata.test_no == 0:
					u.userdata.test_no = 2
			

			elif test_no == "submit":

mysite/xodia/templates/xodia/clickable.html
{%load staticfiles%}<html>

<head>
<title>GROW</title>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">

      <!--Import materialize.css-->

      <link type="text/css" rel="stylesheet" href="{% static 'xodia/css/materialize.min.css' %}" media="screen,projection">

      <link rel="stylesheet" type="text/css" href="{% static 'xodia/css/sweet-alert.css' %}">

      <style type="text/css">

      .top{

        width: 100%;

        height:20%;

        position:relative;

      }



      .card_overlay{

      

        padding-top:2%;

        width: 100%;

      }

      .back{

        position: absolute;

        top:78%;

        right:3%;

      }

      html

      {

        overflow-y: hidden; 

      }

      </style>

    

    </head>

    <body>

      <div class="hide-on-large-only"><h2>PLEASE VIEW IN DESKTOP MODE</h2></div>

<div class="hide-on-med-and-down">

    

    <div class="top teal darken-3 ">

      <div class=" card_overlay">

      <div class="row">

        <div class="col offset-m1 offset-l1 m10 l10">

         <div class="card-panel row blue-grey lighten-5">         



              <div class="col m7 l7 s12 "><canvas id="myCanvas" width="546" height="546" align="center" onclick="savecoord(event)"></canvas>

              </div>

              <div class="col m2 l2">

          <h5>Input</h5>

           <input id="xo1" type="text">

          <br>

          <button class="waves-effect waves-light btn"  onclick="inputbutton()">Grow</button><br>

          </div>

              <div class="col m3 l3 s12  ">

                <h4>SCORE</h4>

                <h5 style="color: red;" id="p1" >Radiant : 0</h5>

                <h5 style="color: #03A9F4;" id="p2">Dire : 0</h5>

                <br>                

            </div>

            <div class = "col m1 l5 s16 ">
                
          <ul class="collection with-header">
        <li class="collection-header"><h5>How to Play</h5></li>
        <li class="collection-item">To pass input use the text box(refer docs for format) or click on the desired points</li>
        <li class="collection-item">For the <b>first move</b>, Select the Root and one leaf(in the first column for p1 and last column for p2). For <b>subsequent moves</b> select one leaf and 2 positions.</li>
        <li class="collection-item">Underlined name indicates turn.</li> 
        <li class="collection-item">Colour convention for <b>nodes,leaves</b>:
        <br>Player 1: <b>Red,Green</b> Player 2: <b>Blue,Yellow</b>. Frozen leaves will be <b>Pink</b> and <b>Cyan</b> respectively.</li>
        <li class="collection-item">To understand the game rules download the docs <a href="{% static 'xodia/pdf/Grow_Documentation.pdf' %}">here</a></li>
      </ul>      



            </div>               

          </div>

          </div>

        </div>

           </div>

    



      <!--Import jQuery before materialize.js-->

      

      <script type="text/javascript" src="{% static 'xodia/js/jquery-2.1.3.min.js'%}"></script>

      <script type="text/javascript" src="{% static 'xodia/js/materialize.min.js'%}"></script>

      <script type ="text/javascript" src="{% static 'xodia/js/sweet-alert.min.js'%}"></script>



       <script type="text/javascript" src=" {% static 'xodia/js/getmousestuff.js'%}"></script>

       <script type="text/javascript" src="{% static 'xodia/js/jscode2.js'%}"></script>

       <script>



       document.getElementById("p1").style.textDecoration = "underline";

var c = document.getElementById("myCanvas");

var ctx = c.getContext("2d");

var k=0;

var l=0;



for(j = 0 ; j < 10 ; j++){

    k=0;

     for (i = 0; i < 10; i++) {

         

        ctx.fillStyle = "#3f3f3b";

        ctx.fillRect(k,l,6,6);

        ctx.fill();

       

        k=k+60;

    }

    l=l+60;

}

$(document).keypress(function(e) {
  if(e.which == 13) {
    // enter pressed
  inputbutton();
  }
});

 </script>

  </div>

  

        <div style="width: 713px;" class="hiddendiv common"></div>
        </body>
        </html>





        

mysite/xodia/templates/xodia/indexlogged.html
{% extends 'xodia/index.html' %}

{% load staticfiles %}


{% block navbar %}
<ul id="nav-mobile1" class="right hide-on-med-and-down" style="position:fixed;z-index:5;left:75%;">
        <li><img src="{% static dppath %}" style="width:30px;position:relative;top:10px;" class="responsive-img circle" />&nbsp{{user.first_name}}</li>
        <li>
          <a class='dropdown-button' href='#' data-activates='dropdown1'><i style="font-size:85%" class="fa fa-chevron-down"></i></a>

                 <ul id='dropdown1' class='dropdown-content'>
              <li><a href="{% url 'xodia:logout' %}">Logout</a></li>
              <li class="divider"></li>
              <li><a class="page-scroll" href="#test" class="event2load"> Testing </a></li>

            </ul></li>
</ul>
{% endblock navbar %}

{% block sidebar %}

<li><img src="{% static dppath %}" style="width:30px;position:relative;top:10px;" class="responsive-img circle" /> </li>
<li>&nbsp{{user.first_name}}</li>

{% endblock sidebar %}

{% block logout %}
<li><a style="color:white;" href="{% url 'xodia:logout' %}"> Logout </a></li>

{%endblock logout %}

mysite/xodia/templates/xodia/nolang.html
{% extends 'xodia/test.html' %}

{% load staticfiles %}

{% block nolang %}
<script type="text/javascript">
	swal("Please select a language","","error");
</script>

{% endblock nolang %}

mysite/xodia/templates/xodia/phomepage.html
{% load staticfiles %}

<h1>Welcome to your personal homepage {{user.first_name}}</h1>

<img src = "{% static path %}"  height="100em" width="100em" />
<img src="{% static 'xodia/apple-icon-57x57.png' %}">
<br/>


{{user.userdata.submitted}}

{% block codeinput %}
You can submit your code below
<form name="codebox" id="codebox">
{% csrf_token %}
<textarea name="code" id="code" rows="1000" cols="100" style ="max-height : 250px ; min-height : 250px resize : none"> </textarea><br/>
<select name="lang">
	<option value="c">c</option>
	<option value="cpp">cpp</option>
	<option value="java">Java</option>
	<option value="python">Python 2.7</option>
	<option value="python3">Python 3</option>
</select>
</form>

{% csrf_token %}
<button type="submit" name="action" value="Test" form="codebox" formaction="{% url 'xodia:test' %}" formmethod="post"> Test </button> 

{% csrf_token %}
<button type="submit" name="submit" value="Submit" form="codebox" formaction="{% url 'xodia:submit' %}" formmethod= "post" > Submit </button> 

{% csrf_token %}

<br/> <br/> <br/> <br/>

{% endblock codeinput %}


<a href = "{% url 'xodia:logout' %}" >Log Out </a>

mysite/xodia/templates/xodia/phomepagesubmitted.html
{% extends 'xodia/phomepage.html' %}

{% block codeinput %}

<h4>You have submitted your final code .... Please sit back and wait for results </h4>

{% endblock %}

mysite/xodia/templates/xodia/signupsuccess.html
<h1>You are successfully Signed up {{user.first_name}}  </h1>

<a href = "{% url 'xodia:loginpage' %}">Please Login to Continue </h1>

mysite/xodia/templates/xodia/test1.html
{% extends 'xodia/test.html' %}

{% block loadgame %}
<div class="card darken-1" style="z-index:1;color:teal;">
<div class="card-content">
                <span class="card-title" style="color:teal;"><b>Get match</b></span>

              </div>
              <div class="card-action">

<form action="{% url 'xodia:getgame' %}" method="post">
{% csrf_token %}
   <input class="with-gap" name="game" required type="radio" id="game1" value="game1" />
   <label for="game1">Test1 vs std</label>
   <input class="btn btn-flat" type="submit" onclick="getgame()" style="color:teal;font-style:italic;" value="Submit" >
</form>
{% csrf_token %}
 </div>
     </div>
<script type="text/javascript">
	function getgame(){
    if(!document.getElementById("game1").checked)
    {
      swal("Oops !","Please select a game","warning");
    }

  }   

</script>
{% endblock loadgame %}

mysite/xodia/templates/xodia/test2.html
{% extends 'xodia/test.html' %}

{% block loadgame %}
<div class="card darken-1" style="z-index:1;color:teal;">
              <div class="card-content">
                <span class="card-title" style="color:teal;"><b>Get match</b></span>

              </div>
          
              <div class="card-action">

<form action="{% url 'xodia:getgame' %}" method="post">
{% csrf_token %}
   <input class="with-gap" required name="game" type="radio" id="game1" value="game1" />
   <label for="game1">Test1 vs std</label>
   <input class="with-gap" required  name="game" type="radio" id="game2" value="game2" />
   <label for="game2">Test2 vs std</label>
   <input class="with-gap" required  name="game" type="radio" id="game3" value="game3" />
   <label for="game3">Test1 vs Test2</label>
   <input class="btn btn-flat" type="submit" onclick="getgame()" style="color:teal;font-style:italic;" value="Submit" >
</form> 
{% csrf_token %}
</div>
</div>
<script type="text/javascript">
  function getgame(){
    if(!document.getElementById("game1").checked && !document.getElementById("game2").checked && !document.getElementById("game3").checked)
    {
      swal("Oops !","Please select a game","warning");
    }

  }   

</script>
{% endblock loadgame %}

mysite/xodia/templates/xodia/uinogame.html
{% extends 'xodia/ui.html'%}

{% block nogame %}
<script type="text/javascript">
swal("No game to display","","warning")	
</script>
{% endblock nogame %}